### ISSUE TITLE
Mock HTTP responses in VPC spec tests.

### ISSUE THREAD

**Issue by agrare** [IBM-Cloud/ibm-cloud-sdk-ruby#12]
https://travis-ci.com/github/IBM-Cloud/ibm-cloud-sdk-ruby/builds/184803842#L348-L360
```
  1) Test vpc API floating_ips can access fetch

     Failure/Error: @data.fetch(:expiration).to_i <= Time.now.to_i + 600

     KeyError:
       key not found: :expiration
     # ./lib/ibm/cloud/sdk/vpc/helpers/connection.rb:54:in `fetch'
     # ./lib/ibm/cloud/sdk/vpc/helpers/connection.rb:54:in `expired?'
     # ./lib/ibm/cloud/sdk/vpc/helpers/connection.rb:58:in `authorization_header'
     # ./lib/ibm/cloud/sdk/vpc/helpers/connection.rb:23:in `adhoc'
     # ./lib/ibm/cloud/sdk/vpc/base_vpc.rb:18:in `adhoc'
     # ./lib/ibm/cloud/sdk/vpc/base_vpc.rb:22:in `get'
     # ./lib/ibm/cloud/sdk/vpc/base_collection.rb:25:in `fetch'
     # ./spec/ibm/cloud/sdk/vpc_spec.rb:53:in `block (3 levels) in <top (required)>'
```
